### ISSUE TITLE
delete a record from ezfind/solr

### ISSUE THREAD

**Issue by dougplant** [mugoweb/eep#37]
* would be nice to have a function that deleted ezfind/solr records
* I just ran into a case where solr was confused by a 'schema change' and the index was corrupted
* reindexing did not work because the index held records that did not exist in my database
* it was a really big database and I did not want to reindex the whole thing
* a workaround was to purge the database and reindex (with eep) the subset of records I was interested in
* (perhaps an index purge would be a useful option, too -- for those occasions when 'updatesearchindexsolr.php --clean-all ...' is hard to find)

**Comment by benkmugo** [comment]
Addressed PR #42
