### ISSUE TITLE
Feature: Manage the object languages (versions in different languages)

### ISSUE THREAD

**Issue by pkamps** [mugoweb/eep#38]
It would be helpful to be able to manipulate the translations of an object. For example, I want to change all Eng-GB translations to Eng-US. Or I want to delete all Eng-GB translations.

There is already something for class translations in eep:
translationcreate, translationsetmain, translationremove

For objects it is probably going to be a bit different. Some similar functions would be very helpful.

**Comment by benkmugo** [comment]
Addressed by PR #43
